### PR TITLE
Use `object-assign`

### PR DESCRIPTION
**Pull request by kevva**
A much nicer way to define options.

### CODE REVIEW

**Comment by ulrikaugustsson** [comment]
Rather keep dependencies to a minimum.

**Comment by nivanson** [comment]
If we were to add dependencies for something like this it would be babel instead and use destructuring.

**Comment by kevva** [comment]
> If we were to add dependencies for something like this it would be babel instead and use destructuring.

Why is including Babel (and thus introducing a need for a compile step before publishing) better than simply doing the "node way" using a module?

**Comment by nivanson** [comment]
I did not say better. I said that's what we would do. Just a preference.

**Pull request closed without merging**
